version: "3.8"

services:
  db:
    platform: linux/amd64
    image: postgres:15
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pZRTXiL6pPoSOCqP
      POSTGRES_DB: internalBookingDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: booking_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      TZ: Asia/Bangkok
      UPLOAD_DIR: /app/attachments
    env_file:
      - .env
    volumes:
      # 🟢 ผูกโฟลเดอร์ uploads ออกมาข้างนอก เพื่อให้รูปภาพ/ไฟล์ไม่หายเวลา Restart
      - ./uploads:/app/uploads
      - "/volume1/Internal Booking System/Internal Booking System/attachments:/app/attachments"
    depends_on:
      - db

volumes:
  pgdata: