version: "3.8"

services:
  db:
    platform: linux/amd64 
    image: postgres:15-alpine
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: booking_system
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: